estore/config/routes.rb
Estore::Application.routes.draw do
  resources :reviews

  resources :posts

  resources :carts

  resources :orders

  resources :lineitems

  get "shop/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/home"

  get "pages/about"

  resources :products

  resources :users

  resources :sessions

	resources :products do
	resources :posts
end

	
	resources :carts do
	resources :lineitems
end

 
  match '/signin', :to => 'sessions#new'
match '/signout', :to => 'sessions#destroy' 
match '/search' => 'products#search'

			

   root :to => 'pages#home'

end

estore/app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :category, :manufacturer, :price, :title, :photo, :rating

  has_many :lineitems
	has_many :orders,  :through => :lineitems
	 has_many :reviews, :dependent => :destroy

	 def self.search(search)
   search_condition = search + "%"
   find(:all, :conditions => ['title LIKE  ?', search_condition])

end

def self.search(search)
   search_condition = search + "%"
   find(:all, :conditions => ['category LIKE  ?', search_condition])
end

	 def self.search(search)
   search_condition = search + "%"
   find(:all, :conditions => ['manufacturer LIKE  ?', search_condition])

end
end

estore/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.order(params[:sort])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end
   
   def search
	@products = Product.search params[:q]
	render 'index'  
                #or whatever view is needed
end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

estore/app/helpers/products_helper.rb
module ProductsHelper
end

estore/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br />
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
    <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

estore/app/views/products/_search.html.erb
<%= form_tag("/search", :method => "get") do %>
   <%= label_tag(:q, "Search for:") %>
   <%= text_field_tag(:q, params[:q], :id => 'q_field') %>
   <%= submit_tag("Search") %>
<% end %> 

estore/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

estore/app/views/products/index.html.erb
<h1>Listing products</h1>
<div id="search">
	<%= render :partial => 'products/search' %>
</div>
<table>
  <tr>
    <th>Title</th>
    <th>Manufacturer</th>
    <th>Price</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.title %></td>
    <td><%= product.manufacturer %></td>
    <td><%= product.price %></td>
    <td><%= product.category %></td>
	 <td><%= image_tag(product.photo, :size=> '200x200') %></td>
    <td><%= link_to 'Show', product %></td>
	 <% if admin? %>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 <% end %>
 </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

estore/app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

estore/app/views/products/show.html.erb
 <div class="star-rating" data-score= <%= @avg_value %> ></div>

<p id="notice"><%= notice %></p>


<p>
  <b>Name:</b>
  <%= @product.title %>
</p>



<p>
  <b>Photo:</b>
<%= image_tag(@product.photo, :size => '100x100') %>
</p>


<p>
  <b>Price:</b>
  <%= @product.price %>
</p>



 <%= link_to "Write a Review", new_review_path %>
</div>
</div>
<div class="col-md-7 col-md-offset-1">
<h1 class="review_name"><%= @product.title %></h1>
<p><%= @product.category %></p>

<% if @product.reviews.empty? %>

<h3>No reviews just yet, would you like to add the first!</h3>
<%= link_to "Write Review", new_review_path, class: "btn btn-danger" %>
<% else %>
  <% @product.reviews.reverse.each do |review| %>

 

</div>
<% end %>
<% end %>
</div>
</div>
</div>
</div>
 <% if admin? %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<% end %>
<%= link_to 'Back', products_path %>