estore/config/routes.rb
Estore::Application.routes.draw do
  resources :reviews

  resources :posts

  resources :carts

  resources :orders

  resources :lineitems

  get "shop/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/home"

  get "pages/about"

  resources :products

  resources :users

  resources :sessions

	resources :products do
	resources :posts
end

	
	resources :carts do
	resources :lineitems
end

 
  match '/signin', :to => 'sessions#new'
match '/signout', :to => 'sessions#destroy' 
match '/search' => 'products#search'

			

   root :to => 'pages#home'

end

estore/app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
  attr_accessible :cart_id, :order_id, :product_id, :quantity
  belongs_to :cart
	belongs_to :order
	belongs_to :product

end

estore/app/controllers/lineitems_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  #include CartController
  before_action :set_cart
  
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    #@line_item = LineItem.new(line_item_params)
	product = Product.find(params[:product_id])
	@line_item = @cart.add_product(product.id)
	#@line_item = @cart.line_items.build(product: product)

    respond_to do |format|
      if @line_item.save
        #format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
		format.html { redirect_to @line_item.cart }
        format.json { render action: 'show', status: :created, location: @line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id)#, :cart_id)
    end
end

estore/app/helpers/lineitems_helper.rb
module LineitemsHelper
end

estore/app/views/lineitems/_form.html.erb
<%= form_for(@lineitem) do |f| %>
  <% if @lineitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lineitem.errors.count, "error") %> prohibited this lineitem from being saved:</h2>

      <ul>
      <% @lineitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br />
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

estore/app/views/lineitems/edit.html.erb
<h1>Editing lineitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @lineitem %> |
<%= link_to 'Back', lineitems_path %>

estore/app/views/lineitems/index.html.erb
<h1>Listing lineitems</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Order</th>
    <th>Quantity</th>
    <th>Cart</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lineitems.each do |lineitem| %>
  <tr>
    <td><%= lineitem.product_id %></td>
    <td><%= lineitem.order_id %></td>
    <td><%= lineitem.quantity %></td>
    <td><%= lineitem.cart_id %></td>
    <td><%= link_to 'Show', lineitem %></td>
    <td><%= link_to 'Edit', edit_lineitem_path(lineitem) %></td>
    <td><%= link_to 'Destroy', lineitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lineitem', new_lineitem_path %>

estore/app/views/lineitems/new.html.erb
<h1>New lineitem</h1>

<%= render 'form' %>

<%= link_to 'Back', lineitems_path %>

estore/app/views/lineitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @lineitem.product_id %>
</p>

<p>
  <b>Order:</b>
  <%= @lineitem.order_id %>
</p>

<p>
  <b>Quantity:</b>
  <%= @lineitem.quantity %>
</p>

<p>
  <b>Cart:</b>
  <%= @lineitem.cart_id %>
</p>


<%= link_to 'Edit', edit_lineitem_path(@lineitem) %> |
<%= link_to 'Back', lineitems_path %>